
---
- name: transfer and unarchive backend
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: start pm2
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start --name "backend" npm -- start