---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install dependencies
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create backend folder"
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "copy backend build"
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend/
    owner: ubuntu

- name: "install npm dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls